// Maps blog post slugs to their unique Gemini-generated images
export const blogImages: Record<string, string> = {
  // Original 10 posts
  "rat-vs-mouse-identifying-rodents-in-your-oc-home": "/images/blog/rat-vs-mouse.jpg",
  "how-rodents-enter-orange-county-attics": "/images/blog/rodents-attic.jpg",
  "argentine-ants-orange-county-why-they-keep-coming-back": "/images/blog/argentine-ants.jpg",
  "spring-pest-prevention-guide-orange-county": "/images/blog/spring-prevention.jpg",
  "year-round-pest-control-schedule-orange-county": "/images/blog/year-round-schedule.jpg",
  "restaurant-pest-control-requirements-orange-county": "/images/blog/restaurant-pest.jpg",
  "how-much-does-pest-control-cost-orange-county": "/images/blog/pest-control-cost.jpg",
  "diy-vs-professional-pest-control-when-to-call-expert": "/images/blog/diy-vs-professional.jpg",
  "eco-friendly-pest-control-options-orange-county": "/images/blog/eco-friendly.jpg",
  "what-to-expect-during-a-pest-inspection": "/images/blog/pest-inspection.jpg",
  // 20 new posts
  "health-risks-of-rodent-infestations-in-southern-california": "/images/blog/health-risks-rodents.jpg",
  "fire-ant-prevention-tips-for-oc-homeowners": "/images/blog/fire-ants.jpg",
  "summer-pest-control-mosquitoes-ants-more-in-oc": "/images/blog/summer-pests.jpg",
  "fall-rodent-prevention-keep-mice-out-before-winter": "/images/blog/fall-rodent-prevention.jpg",
  "commercial-pest-control-for-oc-property-managers": "/images/blog/commercial-property.jpg",
  "how-to-choose-a-commercial-exterminator-in-orange-county": "/images/blog/choosing-exterminator.jpg",
  "signs-of-termite-damage-in-orange-county-homes": "/images/blog/termite-damage.jpg",
  "black-widow-spiders-in-orange-county": "/images/blog/black-widow.jpg",
  "bed-bug-prevention-tips-for-orange-county-hotels-and-homes": "/images/blog/bed-bug-prevention.jpg",
  "how-to-pest-proof-your-orange-county-home-this-winter": "/images/blog/winter-pest-proof.jpg",
  "the-complete-guide-to-cockroach-control-in-orange-county": "/images/blog/cockroach-guide.jpg",
  "why-wasps-are-more-aggressive-in-late-summer": "/images/blog/wasps-aggressive.jpg",
  "raccoons-in-orange-county-prevention-and-removal": "/images/blog/raccoons-oc.jpg",
  "how-to-keep-spiders-out-of-your-garage": "/images/blog/spiders-garage.jpg",
  "understanding-flea-and-tick-season-in-southern-california": "/images/blog/flea-tick-season.jpg",
  "top-5-pest-entry-points-in-orange-county-homes": "/images/blog/pest-entry-points.jpg",
  "is-that-a-termite-or-a-flying-ant": "/images/blog/termite-vs-ant.jpg",
  "pet-safe-pest-control-methods-for-orange-county-families": "/images/blog/pet-safe-pest.jpg",
  "the-hidden-dangers-of-diy-pest-control-products": "/images/blog/diy-dangers.jpg",
  "orange-countys-most-common-summer-pests-2026-update": "/images/blog/summer-pests-2026.jpg",
};
