export const SITE_CONFIG = {
  name: "Yogi's Pest Control",
  phone: "714-323-8262",
  phoneTel: "tel:7143238262",
  email: "yobanla@yogispestcontrol.com",
  address: {
    street: "",
    city: "Orange County",
    state: "CA",
    zip: "",
  },
  hours: "Open 7 Days A Week 8AM-8PM",
  url: "https://yogispestcontrol.com",
  social: {
    facebook: "",
    instagram: "",
    google: "",
    yelp: "",
  },
} as const;

export const SERVICES = [
  { slug: "rodent-control", name: "Rodent Control", shortDesc: "Rats, mice & rodent removal", icon: "rat" },
  { slug: "cockroach-control", name: "Cockroach Control", shortDesc: "Complete roach elimination", icon: "bug" },
  { slug: "ant-control", name: "Ant Control", shortDesc: "All ant species treatment", icon: "ant" },
  { slug: "wasp-control", name: "Wasp Control", shortDesc: "Safe wasp nest removal", icon: "wasp" },
  { slug: "bee-removal", name: "Bee Removal", shortDesc: "Humane bee relocation", icon: "bee" },
  { slug: "mosquito-control", name: "Mosquito Control", shortDesc: "Yard & outdoor treatment", icon: "mosquito" },
  { slug: "fly-control", name: "Fly Control", shortDesc: "Indoor & outdoor fly solutions", icon: "fly" },
  { slug: "spider-control", name: "Spider Control", shortDesc: "Common & venomous spiders", icon: "spider" },
  { slug: "tick-flea-treatment", name: "Tick & Flea Treatment", shortDesc: "Home & pet protection", icon: "tick" },
  { slug: "exclusion-repairs", name: "Exclusion Repairs", shortDesc: "Seal entry points", icon: "shield" },
  { slug: "attic-cleanout", name: "Attic Cleanouts", shortDesc: "Waste removal & sanitation", icon: "home" },
  { slug: "bed-bug-treatment", name: "Bed Bug Treatment", shortDesc: "Complete bed bug eradication", icon: "bed" },
  { slug: "wildlife-trapping", name: "Wildlife Trapping", shortDesc: "Humane wildlife capture", icon: "wildlife" },
  { slug: "dead-animal-removal", name: "Dead Animal Removal", shortDesc: "Safe removal & cleanup", icon: "cleanup" },
] as const;

export const OC_CITIES = [
  { slug: "anaheim", name: "Anaheim", population: 350000, priority: "high" },
  { slug: "santa-ana", name: "Santa Ana", population: 310000, priority: "high" },
  { slug: "irvine", name: "Irvine", population: 310000, priority: "high" },
  { slug: "huntington-beach", name: "Huntington Beach", population: 198000, priority: "high" },
  { slug: "garden-grove", name: "Garden Grove", population: 172000, priority: "high" },
  { slug: "orange", name: "Orange", population: 139000, priority: "high" },
  { slug: "fullerton", name: "Fullerton", population: 139000, priority: "high" },
  { slug: "costa-mesa", name: "Costa Mesa", population: 113000, priority: "high" },
  { slug: "mission-viejo", name: "Mission Viejo", population: 96000, priority: "medium" },
  { slug: "westminster", name: "Westminster", population: 91000, priority: "medium" },
  { slug: "newport-beach", name: "Newport Beach", population: 85000, priority: "medium" },
  { slug: "buena-park", name: "Buena Park", population: 82000, priority: "medium" },
  { slug: "lake-forest", name: "Lake Forest", population: 85000, priority: "medium" },
  { slug: "tustin", name: "Tustin", population: 80000, priority: "medium" },
  { slug: "yorba-linda", name: "Yorba Linda", population: 68000, priority: "medium" },
  { slug: "san-clemente", name: "San Clemente", population: 65000, priority: "medium" },
  { slug: "laguna-niguel", name: "Laguna Niguel", population: 65000, priority: "medium" },
  { slug: "la-habra", name: "La Habra", population: 63000, priority: "medium" },
  { slug: "fountain-valley", name: "Fountain Valley", population: 57000, priority: "medium" },
  { slug: "placentia", name: "Placentia", population: 52000, priority: "low" },
  { slug: "rancho-santa-margarita", name: "Rancho Santa Margarita", population: 48000, priority: "low" },
  { slug: "aliso-viejo", name: "Aliso Viejo", population: 51000, priority: "low" },
  { slug: "cypress", name: "Cypress", population: 49000, priority: "low" },
  { slug: "brea", name: "Brea", population: 47000, priority: "low" },
  { slug: "dana-point", name: "Dana Point", population: 34000, priority: "low" },
  { slug: "san-juan-capistrano", name: "San Juan Capistrano", population: 36000, priority: "low" },
  { slug: "laguna-beach", name: "Laguna Beach", population: 23000, priority: "low" },
  { slug: "laguna-hills", name: "Laguna Hills", population: 31000, priority: "low" },
  { slug: "seal-beach", name: "Seal Beach", population: 25000, priority: "low" },
  { slug: "los-alamitos", name: "Los Alamitos", population: 12000, priority: "low" },
  { slug: "stanton", name: "Stanton", population: 39000, priority: "low" },
  { slug: "la-palma", name: "La Palma", population: 15000, priority: "low" },
  { slug: "villa-park", name: "Villa Park", population: 6000, priority: "low" },
  { slug: "ladera-ranch", name: "Ladera Ranch", population: 30000, priority: "low" },
] as const;

export const GUARANTEE_BADGES = [
  { label: "Same-Day Response", icon: "clock" },
  { label: "100% Satisfaction Guarantee", icon: "check-circle" },
  { label: "Eco-Friendly Products", icon: "leaf" },
  { label: "Licensed & Insured", icon: "shield-check" },
  { label: "Family & Pet Safe", icon: "heart" },
  { label: "Free Inspections", icon: "search" },
] as const;
